routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['prefix'=>'admin','middleware'=>['isVerified','auth']],function(){

    Route::get('/','Admin\HomeController@index')->name('admin.home.index');
    Route::resource('user','Admin\UserController');
    Route::resource('categories', 'Admin\CategoriesController');
    Route::resource('series', 'Admin\SeriesController');
    Route::get('series/{serie}/thumb_asset','Admin\SeriesController@thumb_asset')->name('series.thumb_asset');
    Route::get('series/{serie}/thumb_small_asset','Admin\SeriesController@thumb_small_asset')->name('series.thumb_small_asset');
    Route::get('videos/{video}/thumb_asset','Admin\VideosController@thumb_asset')->name('videos.thumb_asset');
    Route::get('videos/{video}/thumb_small_asset','Admin\VideosController@thumb_small_asset')->name('videos.thumb_small_asset');
    Route::get('videos/{video}/file_asset','Admin\VideosController@file_asset')->name('videos.file_asset');


    Route::group(['prefix'=>'videos', 'as'=>'videos.'], function(){
        Route::name('relations.create')->get('{video}/relations','Admin\VideoRelationsController@create');
        Route::name('relations.store')->post('{video}/relations','Admin\VideoRelationsController@store');
        Route::name('uploads.create')->get('{video}/uploads','Admin\VideoUploadsController@create');
        Route::name('uploads.store')->post('{video}/uploads','Admin\VideoUploadsController@store');
    });
    Route::resource('videos','Admin\VideosController');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::get('email-verification/error', 'EmailVerificationController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'EmailVerificationController@getVerification')->name('email-verification.check');

app/Models/Video.php
<?php

namespace App\Models;

use Bootstrapper\Interfaces\TableInterface;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;
use App\Media\VideoPaths;

class Video extends Model implements TableInterface
{
    use TransformableTrait, VideoPaths, SoftDeletes;

    protected $fillable = [
        'id',
		'title',
		'description',
		'duration',
        'file',
        'thumb',
        'serie_id',

	];

    protected $casts = [
        'completed'=>'boolean'
    ];

    public function serie(){
        return $this->belongsTo(Serie::class,'serie_id','id');
    }

    public function categories(){
        return $this->belongsToMany(Category::class);
    }

    /**
     * A list of headers to be used when a table is displayed
     *
     * @return array
     */
    public function getTableHeaders()
    {
      return ['#'];
    }

    /**
     * Get the value for a given header. Note that this will be the value
     * passed to any callback functions that are being used.
     *
     * @param string $header
     * @return mixed
     */
    public function getValueForHeader($header)
    {
       switch($header){
           case '#':
               return $this->id;

               break;
       }
    }
}

app/Http/Controllers/Admin/VideosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Forms\VideoForm;
use App\Http\Controllers\Controller;
use App\Models\Video;
use App\Repositories\VideoRepository;
use FormBuilder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class VideosController extends Controller
{
    protected $repository;
    public function __construct(VideoRepository $repository)
    {
        $this->repository = $repository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $videos = $this->repository->paginate();
        return view('admin.videos.index', compact('videos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $form = FormBuilder::create(VideoForm::class,[
            'url'=>route('videos.store'),
            'method'=>'POST',
        ]);
        return view('admin.videos.create',compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = FormBuilder::create(VideoForm::class);
        if(!$form->isValid()){
            return redirect()
                ->back()
                ->withErrors($form->getErrors())
                ->withInput();
        }

        $data = $form->getFieldValues();
        $data['thumb'] = "thumb.jpg";
        Model::unguard();
        $this->repository->create($data);
        $request->session()->flash('message','Vídeo criado!');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Video  $videos
     * @return \Illuminate\Http\Response
     */
    public function show(Video $video)
    {
        if (request()->wantsJson()) {

            return response()->json([
                'data' => $video,
            ]);
        }
        return view('admin.videos.show',compact('video'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Video  $videos
     * @return \Illuminate\Http\Response
     */
    public function edit(Video $video)
    {
        $form = FormBuilder::create(VideoForm::class,[
            'url'=>route('videos.update',['video'=>$video->id]),
            'method'=>'PUT',
            'model'=> $video
        ]);

        return view('admin.videos.edit',compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form = FormBuilder::create(VideoForm::class, [
            'data' => ['id' => $id]
        ]);
        if(!$form->isValid()){
            return redirect()
                ->back()
                ->withErrors($form->getErrors())
                ->withInput();
        }

        $data = $form->getFieldValues();

        $this->repository->update($data,$id);

        $request->session()->flash('message','Vídeo atualizado!');

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Video  $video
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $request->session()->flash('message','Vídeo deletado!');
        $this->repository->delete($id);
        return redirect()->route('videos.index');
    }

    public function file_asset(Video $video){
        return response()->download($video->file_path);

    }

    public function thumb_asset(Video $video){
        return response()->download($video->thumb_path);

    }
    public function thumb_small_asset(Video $video){
        return response()->download($video->thumb_small_path);

    }
}

resources/views/admin/videos/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            @component('admin.videos.tabs-component')
                <div class="col-md-12">
            <h3>Novo Vídeo</h3>
            @php $icon = Icon::create('floppy-disk') @endphp
            {!! form($form->add('salvar','submit',[
                           'attr' => ['class'=>'btn btn-primary btn-block'],
                           'label' => $icon,
                       ]))
            !!}
                </div>
            @endcomponent
        </div>
    </div>
@endsection

resources/views/admin/videos/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            @component('admin.videos.tabs-component',['video'=>$form->getModel()])
                <div class="col-md-12">
                    <h3>Editar Vídeo</h3>
                    @php $icon = Icon::create('edit') @endphp
                    {!! form($form->add('salvar','submit',[
                                   'attr' => ['class'=>'btn btn-primary btn-block'],
                                   'label' => $icon,
                               ]))
                    !!}
                </div>
            @endcomponent
        </div>
    </div>
@endsection

resources/views/admin/videos/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <h3 style="  display: inline-block;">Vídeos </h3>
        {!! Button::primary('Novo')->asLinkTo(route('videos.create')) !!}
        <div class="row">
            {!! Table::withContents($videos->items())
            ->striped()
            ->callback('Descriçao', function($field,$videos){
           return MediaObject::withContents([
            'image'=>$videos->small_asset,
            'link'=>$videos->file_asset,
            'heading'=>$videos->title,
            'body'=>$videos->description,
            ]);
            })
            ->callback('Ações',function($field,$videos){
                $linkEdit = route('videos.edit',['video'=>$videos->id]);
                $linkShow = route('videos.show',['video'=>$videos->id]);
                return  Button::link(Icon::create('edit'))
                ->asLinkTo($linkEdit).''.
                Button::link(Icon::create('remove'))
                ->asLinkTo($linkShow);
            })!!}
        </div>
        {!! $videos->links() !!}
    </div>
@endsection

@push('styles')
<style type="text/css">
    table > thead > tr > th:nth-child(2){
        width: 80%;
    }
    .media-body{
        width: auto;
    }
</style>
@endpush

resources/views/admin/videos/relation.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            @component('admin.videos.tabs-component',['video'=>$form->getModel()])
                <div class="col-md-12">
            <h3>Série e categorias</h3>
            @php $icon = Icon::create('edit') @endphp
            {!! form($form->add('salvar','submit',[
                           'attr' => ['class'=>'btn btn-primary btn-block'],
                           'label' => $icon,
                       ]))
            !!}
                </div>
            @endcomponent
        </div>
    </div>
@endsection

resources/views/admin/videos/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <h3>Ver vídeos</h3>

        @php $formDelete = FormBuilder::plain([
            'route'=>['videos.destroy','category'=>$video->id],
            'method'=>'DELETE',
            'id'=>'formDelete',
            'style'=>'display:none'
            ]) @endphp

        {!! form($formDelete) !!}
        <div class="row">
            <table class="table table-bordered">
                <tbody>

                <tr>
                    <th scope="row">#</th>
                    <td>{{$video->id}}</td>
                </tr>
                <tr>
                    <th scope="row">Título</th>
                    <td>{{$video->title}}</td>
                </tr>
                <tr>
                    <th scope="row">Thumbnail</th>
                    <td><img class="img-responsive img-thumbnail" src="{{$video->thumb_asset}}"></td>
                </tr>
                <tr>
                    <th scope="row">Download</th>
                    <td><a href="{{$video->file_asset}}">Clique aqui</a></td>
                </tr>
                <tr>
                    <th scope="row">Descrição</th>
                    <td>{{$video->description}}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="row">
            @php $iconEdit = Icon::create('edit') @endphp
            {!! Button::normal($iconEdit)->asLinkTo(route('videos.edit',['video'=>$video->id])) !!}
            @php $iconDestroy = Icon::create('remove') @endphp
            {!! Button::danger($iconDestroy)
             ->addAttributes(['onclick'=> "sendDelete()"])!!}
        </div>
    </div>
    <script>

            function sendDelete(){
                document.getElementById('formDelete').submit();
            }

    </script>
@endsection

resources/views/admin/videos/tabs-component.blade.php
<?php
$tabs = [
    [
        'title'=>'Informações',
        'link'=> isset($video) ? route('videos.edit',['video'=>$video->id]) : route('videos.create'),
    ],
    [
        'title'=>'Série e Categorias',
        'link'=>  isset($video) ? route('videos.relations.create',['video'=>$video->id]) : '#',
        'disable' => isset($video) ? false : true,
    ],
    [
        'title'=> 'Vídeo e Thumbnail',
        'link'=> isset($video) ? route('videos.uploads.create',['video'=>$video->id]) : '#',
        'disable' =>  isset($video) ? false : true,
    ],
];
?>
<h3>Gerenciar Vídeo</h3>
<div class="text-right">
    {!! Button::link('Listar vídeos')->asLinkTo(route('videos.index')) !!}
</div>
{!! Navigation::tabs($tabs) !!}
<div>
    {!! $slot !!}
</div>

resources/views/admin/videos/upload.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            @component('admin.videos.tabs-component',['video'=>$form->getModel()])
                <div class="col-md-12">
                    <h3>Thumbnail e arquivo de vídeo</h3>
                    @php $icon = Icon::create('edit') @endphp
                    {!! form($form->add('salvar','submit',[
                                   'attr' => ['class'=>'btn btn-primary btn-block'],
                                   'label' => $icon,
                               ]))
                    !!}
                </div>
            @endcomponent
        </div>
    </div>
@endsection