routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['prefix'=>'admin','middleware'=>['isVerified','auth']],function(){

    Route::get('/','Admin\HomeController@index')->name('admin.home.index');
    Route::resource('user','Admin\UserController');
    Route::resource('categories', 'Admin\CategoriesController');
    Route::resource('series', 'Admin\SeriesController');
    Route::get('series/{serie}/thumb_asset','Admin\SeriesController@thumb_asset')->name('series.thumb_asset');
    Route::get('series/{serie}/thumb_small_asset','Admin\SeriesController@thumb_small_asset')->name('series.thumb_small_asset');
    Route::get('videos/{video}/thumb_asset','Admin\VideosController@thumb_asset')->name('videos.thumb_asset');
    Route::get('videos/{video}/thumb_small_asset','Admin\VideosController@thumb_small_asset')->name('videos.thumb_small_asset');
    Route::get('videos/{video}/file_asset','Admin\VideosController@file_asset')->name('videos.file_asset');


    Route::group(['prefix'=>'videos', 'as'=>'videos.'], function(){
        Route::name('relations.create')->get('{video}/relations','Admin\VideoRelationsController@create');
        Route::name('relations.store')->post('{video}/relations','Admin\VideoRelationsController@store');
        Route::name('uploads.create')->get('{video}/uploads','Admin\VideoUploadsController@create');
        Route::name('uploads.store')->post('{video}/uploads','Admin\VideoUploadsController@store');
    });
    Route::resource('videos','Admin\VideosController');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::get('email-verification/error', 'EmailVerificationController@getVerificationError')->name('email-verification.error');
Route::get('email-verification/check/{token}', 'EmailVerificationController@getVerification')->name('email-verification.check');

app/Models/User.php
<?php

namespace App\Models;

use App\Notifications\DefaultResetPasswordNotification;
use Bootstrapper\Interfaces\TableInterface;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject;


class User extends Authenticatable implements TableInterface, JWTSubject
{
    use Notifiable;

    const ADMIN =1;
    const CLIENT=0;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function sendPasswordResetNotification($token)
    {
        $this->notify(new DefaultResetPasswordNotification($token));
    }

    /**
     * A list of headers to be used when a table is displayed
     *
     * @return array
     */
    public function getTableHeaders()
    {
        return ['#','Nome','Email'];
    }

    /**
     * Get the value for a given header. Note that this will be the value
     * passed to any callback functions that are being used.
     *
     * @param string $header
     * @return mixed
     */
    public function getValueForHeader($header)
    {
        switch ($header){
            case '#':
                return $this->id;
            case 'Nome':
                return $this->name;
            case 'Email':
                return $this->email;

        }
    }

    public static function generatePassword($password = null){
        return !$password ? bcrypt(str_random(8)) : bcrypt($password);
    }

    /**
     * @param  array $payload
     * @return string
     */

    /**
     * Get the identifier that will be stored in the subject claim of the JWT.
     *
     * @return mixed
     */
    public function getJWTIdentifier()
    {
        return $this->id;
    }

    /**
     * Return a key value array, containing any custom claims to be added to the JWT.
     *
     * @return array
     */
    public function getJWTCustomClaims()
    {
        return [
            'user'=>[
                'id'=>$this->id,
                'name'=>$this->name,
                'email'=>$this->email,
                'role'=>$this->role,
            ]
        ];
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Forms\UserForm;
use App\Models\User;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Kris\LaravelFormBuilder\Facades\FormBuilder;

class UserController extends Controller
{
    protected $repository;
    public function __construct(UserRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cUser = $this->repository->paginate();
        return view('admin.users.index')->with('users',$cUser);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $form = FormBuilder::create(UserForm::class,[
            'url'=>route('user.store'),
            'method'=>'POST',
        ]);
        return view('admin.users.create',compact('form'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $form = FormBuilder::create(UserForm::class);
        if(!$form->isValid()){
            return redirect()
                ->back()
                ->withErrors($form->getErrors())
                ->withInput();
        }

        $data = $form->getFieldValues();


        $this->repository->create($data);

        $request->session()->flash('message','Usuário administrativo criado com sucesso!');

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $user = array_except($user,['password']);
        $form = FormBuilder::create(UserForm::class,[
            'url'=>route('user.update',['user'=>$user->id]),
            'method'=>'PUT',
            'model'=>$user
        ]);
        return view('admin.users.edit',compact('form'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $form = FormBuilder::create(UserForm::class, [
            'data' => ['id' => $id]
        ]);
        if(!$form->isValid()){
            return redirect()
                ->back()
                ->withErrors($form->getErrors())
                ->withInput();
        }

        $data = array_except($form->getFieldValues(),['role']);

        $this->repository->update($data,$id);

        $request->session()->flash('message','Usuário administrativo atualizado com sucesso!');

        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $request->session()->flash('message','Usuário administrativo deletado com sucesso!');
        $this->repository->delete($id);
        return redirect()->route('user.index');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <h3>Novo usuário</h3>
            @php $icon = Icon::create('floppy-disk') @endphp
            {!! form($form->add('salvar','submit',[
                           'attr' => ['class'=>'btn btn-primary btn-block'],
                           'label' => $icon,
                       ]))
            !!}
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <h3>Editar usuário</h3>
            @php $icon = Icon::create('edit') @endphp
            {!! form($form->add('salvar','submit',[
                           'attr' => ['class'=>'btn btn-primary btn-block'],
                           'label' => $icon,
                       ]))
            !!}
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <h3 style="  display: inline-block;">Usuários </h3>
        {!! Button::primary('Novo')->asLinkTo(route('user.create')) !!}
        <div class="row">
            {!! Table::withContents($users->items())
            ->striped()
            ->callback('Ações',function($field,$user){
                $linkEdit = route('user.edit',['user'=>$user->id]);
                $linkShow = route('user.show',['user'=>$user->id]);
                return  Button::link(Icon::create('edit'))
                ->asLinkTo($linkEdit).''

                .Button::link(Icon::create('remove'))
                ->asLinkTo($linkShow);
            })!!}
        </div>
        {!! $users->links() !!}
    </div>
@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <h3>Ver usuário</h3>

        @php $formDelete = FormBuilder::plain([
            'route'=>['user.destroy','user'=>$user->id],
            'method'=>'DELETE',
            'id'=>'formDelete',
            'style'=>'display:none'
            ]) @endphp

        {!! form($formDelete) !!}
        <div class="row">
            <table class="table table-bordered">
                <tbody>
                <tr>
                    <th scope="row">#</th>
                    <td>{{$user->id}}</td>
                </tr>
                <tr>
                    <th scope="row">Nome</th>
                    <td>{{$user->name}}</td>
                </tr>
                <tr>
                    <th scope="row">E-mail</th>
                    <td>{{$user->email}}</td>
                </tr>
                <tr>
                    <th scope="row">Papel</th>
                    <td>{{$user->role==1 ? "Administrador" : "Cliente"}}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="row">
            @php $iconEdit = Icon::create('edit') @endphp
            {!! Button::normal($iconEdit)->asLinkTo(route('user.edit',['user'=>$user->id])) !!}
            @php $iconDestroy = Icon::create('remove') @endphp
            {!! Button::danger($iconDestroy)
             ->addAttributes(['onclick'=> "sendDelete()"])!!}
        </div>
    </div>
    <script>

            function sendDelete(){
                document.getElementById('formDelete').submit();
            }

    </script>
@endsection